micronaut:
  application:
    name: carrosGrpc

datasources:
  default:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/carrosGrpc?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: ${DB_PASSWORD:safadotaba}
    schema-generate: CREATE_DROP
    dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"

jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.show_sql: true
      hibernate.format_sql: true
